# Generated by Django 3.2.15 on 2022-08-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Photoc',
        ),
    ]
